/*
* Copyright (c) 2000 - 2005 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:  
 *
*/


/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nokia_comm_wap_wps_Transaction */

#ifndef _Included_com_nokia_comm_wap_wps_Transaction
#define _Included_com_nokia_comm_wap_wps_Transaction
#ifdef __cplusplus
extern "C" {
#endif
#undef com_nokia_comm_wap_wps_Transaction_DATA_UNKNOWN
#define com_nokia_comm_wap_wps_Transaction_DATA_UNKNOWN 0L
#undef com_nokia_comm_wap_wps_Transaction_DATA_PUSH_BODY
#define com_nokia_comm_wap_wps_Transaction_DATA_PUSH_BODY 1L
#undef com_nokia_comm_wap_wps_Transaction_DATA_PUSH_HEADERS
#define com_nokia_comm_wap_wps_Transaction_DATA_PUSH_HEADERS 2L
#undef com_nokia_comm_wap_wps_Transaction_DATA_RESULT_STATUS
#define com_nokia_comm_wap_wps_Transaction_DATA_RESULT_STATUS 3L
#undef com_nokia_comm_wap_wps_Transaction_DATA_RESULT_BODY
#define com_nokia_comm_wap_wps_Transaction_DATA_RESULT_BODY 4L
#undef com_nokia_comm_wap_wps_Transaction_DATA_RESULT_HEADERS
#define com_nokia_comm_wap_wps_Transaction_DATA_RESULT_HEADERS 5L
#undef com_nokia_comm_wap_wps_Transaction_DATA_INVOKE_URI
#define com_nokia_comm_wap_wps_Transaction_DATA_INVOKE_URI 6L
#undef com_nokia_comm_wap_wps_Transaction_DATA_INVOKE_METHOD
#define com_nokia_comm_wap_wps_Transaction_DATA_INVOKE_METHOD 7L
#undef com_nokia_comm_wap_wps_Transaction_DATA_INVOKE_HEADERS
#define com_nokia_comm_wap_wps_Transaction_DATA_INVOKE_HEADERS 8L
#undef com_nokia_comm_wap_wps_Transaction_DATA_INVOKE_BODY
#define com_nokia_comm_wap_wps_Transaction_DATA_INVOKE_BODY 9L
#undef com_nokia_comm_wap_wps_Transaction_DATA_ACK_HEADERS
#define com_nokia_comm_wap_wps_Transaction_DATA_ACK_HEADERS 10L
#undef com_nokia_comm_wap_wps_Transaction_DATA_ABORT_REASON
#define com_nokia_comm_wap_wps_Transaction_DATA_ABORT_REASON 11L
#undef com_nokia_comm_wap_wps_Transaction_STATE_UNKNOWN
#define com_nokia_comm_wap_wps_Transaction_STATE_UNKNOWN 0L
#undef com_nokia_comm_wap_wps_Transaction_STATE_INIT
#define com_nokia_comm_wap_wps_Transaction_STATE_INIT 1L
#undef com_nokia_comm_wap_wps_Transaction_STATE_DONE
#define com_nokia_comm_wap_wps_Transaction_STATE_DONE 2L
#undef com_nokia_comm_wap_wps_Transaction_STATE_REPLYING
#define com_nokia_comm_wap_wps_Transaction_STATE_REPLYING 3L
#undef com_nokia_comm_wap_wps_Transaction_STATE_ABORTING
#define com_nokia_comm_wap_wps_Transaction_STATE_ABORTING 4L
#undef com_nokia_comm_wap_wps_Transaction_STATE_ABORTED
#define com_nokia_comm_wap_wps_Transaction_STATE_ABORTED 5L
#undef com_nokia_comm_wap_wps_Transaction_STATE_PROCESSING
#define com_nokia_comm_wap_wps_Transaction_STATE_PROCESSING 6L
/* Inaccessible static: exceptionMessage */
/*
 * Class:     com_nokia_comm_wap_wps_Transaction
 * Method:    wspAbort
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_nokia_comm_wap_wps_Transaction_wspAbort
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_nokia_comm_wap_wps_Transaction
 * Method:    wspExecuteTransaction
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_nokia_comm_wap_wps_Transaction_wspExecuteTransaction
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_nokia_comm_wap_wps_Transaction
 * Method:    wspGetTransactionData
 * Signature: (IILcom/nokia/comm/wap/wps/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_nokia_comm_wap_wps_Transaction_wspGetTransactionData
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_nokia_comm_wap_wps_Transaction
 * Method:    wspGetTransactionOwner
 * Signature: (ILcom/nokia/comm/wap/wps/Session;)I
 */
JNIEXPORT jint JNICALL Java_com_nokia_comm_wap_wps_Transaction_wspGetTransactionOwner
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_nokia_comm_wap_wps_Transaction
 * Method:    wspGetTransactionState
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_nokia_comm_wap_wps_Transaction_wspGetTransactionState
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_nokia_comm_wap_wps_Transaction
 * Method:    wspReleaseTransaction
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_nokia_comm_wap_wps_Transaction_wspReleaseTransaction
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_nokia_comm_wap_wps_Transaction
 * Method:    wspSetMethodResult
 * Signature: (IILcom/nokia/comm/wap/wps/ByteBuffer;Lcom/nokia/comm/wap/wps/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_nokia_comm_wap_wps_Transaction_wspSetMethodResult
  (JNIEnv *, jobject, jint, jint, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
