/*
* Copyright (c) 2000 - 2005 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:  
 *
*/


/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nokia_comm_wap_wps_ExceptionEvent */

#ifndef _Included_com_nokia_comm_wap_wps_ExceptionEvent
#define _Included_com_nokia_comm_wap_wps_ExceptionEvent
#ifdef __cplusplus
extern "C" {
#endif
#undef com_nokia_comm_wap_wps_ExceptionEvent_DATA_UNKNOWN
#define com_nokia_comm_wap_wps_ExceptionEvent_DATA_UNKNOWN 0L
#undef com_nokia_comm_wap_wps_ExceptionEvent_DATA_EXCEPTION
#define com_nokia_comm_wap_wps_ExceptionEvent_DATA_EXCEPTION 1L
/* Inaccessible static: exceptionMessage */
/*
 * Class:     com_nokia_comm_wap_wps_ExceptionEvent
 * Method:    wspGetExceptionData
 * Signature: (IILcom/nokia/comm/wap/wps/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_nokia_comm_wap_wps_ExceptionEvent_wspGetExceptionData
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_nokia_comm_wap_wps_ExceptionEvent
 * Method:    wspGetExceptionOwner
 * Signature: (ILcom/nokia/comm/wap/wps/Session;)I
 */
JNIEXPORT jint JNICALL Java_com_nokia_comm_wap_wps_ExceptionEvent_wspGetExceptionOwner
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_nokia_comm_wap_wps_ExceptionEvent
 * Method:    wspReleaseException
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_nokia_comm_wap_wps_ExceptionEvent_wspReleaseException
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
