/*
* Copyright (c) 2000 - 2005 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:  
 *
*/


/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nokia_wap_sdk_util_HelperProcess */

#ifndef _Included_com_nokia_wap_sdk_util_HelperProcess
#define _Included_com_nokia_wap_sdk_util_HelperProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nokia_wap_sdk_util_HelperProcess
 * Method:    cCreateProcess
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_nokia_wap_sdk_util_HelperProcess_cCreateProcess
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_nokia_wap_sdk_util_HelperProcess
 * Method:    cTerminateProcess
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_nokia_wap_sdk_util_HelperProcess_cTerminateProcess
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
