/*
* Copyright (c) 2000 - 2005 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:  
 *
*/


/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nokia_comm_wap_wps_Bearer */

#ifndef _Included_com_nokia_comm_wap_wps_Bearer
#define _Included_com_nokia_comm_wap_wps_Bearer
#ifdef __cplusplus
extern "C" {
#endif
#undef com_nokia_comm_wap_wps_Bearer_WDP_D_MAX_RECEIVE_BUFFER_LENGTH
#define com_nokia_comm_wap_wps_Bearer_WDP_D_MAX_RECEIVE_BUFFER_LENGTH 0L
#undef com_nokia_comm_wap_wps_Bearer_WDP_D_MAX_SEND_BUFFER_LENGTH
#define com_nokia_comm_wap_wps_Bearer_WDP_D_MAX_SEND_BUFFER_LENGTH 1L
#undef com_nokia_comm_wap_wps_Bearer_WDP_D_MAX_RECEIVE_ADDRESS_LENGTH
#define com_nokia_comm_wap_wps_Bearer_WDP_D_MAX_RECEIVE_ADDRESS_LENGTH 2L
#undef com_nokia_comm_wap_wps_Bearer_WDP_D_MAX_SEND_ADDRESS_LENGTH
#define com_nokia_comm_wap_wps_Bearer_WDP_D_MAX_SEND_ADDRESS_LENGTH 3L
#undef com_nokia_comm_wap_wps_Bearer_WDP_D_MAX_ACK_TIMER_EXPIRATIONS
#define com_nokia_comm_wap_wps_Bearer_WDP_D_MAX_ACK_TIMER_EXPIRATIONS 4L
#undef com_nokia_comm_wap_wps_Bearer_WDP_D_MAX_RETRANSMISSIONS
#define com_nokia_comm_wap_wps_Bearer_WDP_D_MAX_RETRANSMISSIONS 5L
#undef com_nokia_comm_wap_wps_Bearer_WDP_D_TIMER_ACK_T
#define com_nokia_comm_wap_wps_Bearer_WDP_D_TIMER_ACK_T 6L
#undef com_nokia_comm_wap_wps_Bearer_WDP_D_TIMER_U_ACK_T
#define com_nokia_comm_wap_wps_Bearer_WDP_D_TIMER_U_ACK_T 7L
#undef com_nokia_comm_wap_wps_Bearer_WDP_D_TIMER_S_ACK_T
#define com_nokia_comm_wap_wps_Bearer_WDP_D_TIMER_S_ACK_T 8L
#undef com_nokia_comm_wap_wps_Bearer_WDP_D_TIMER_L_ACK_T
#define com_nokia_comm_wap_wps_Bearer_WDP_D_TIMER_L_ACK_T 9L
#undef com_nokia_comm_wap_wps_Bearer_WDP_D_TIMER_TTR_T
#define com_nokia_comm_wap_wps_Bearer_WDP_D_TIMER_TTR_T 10L
#undef com_nokia_comm_wap_wps_Bearer_WDP_D_TIMER_S_TTR_T
#define com_nokia_comm_wap_wps_Bearer_WDP_D_TIMER_S_TTR_T 11L
#undef com_nokia_comm_wap_wps_Bearer_WDP_D_TIMER_L_TTR_T
#define com_nokia_comm_wap_wps_Bearer_WDP_D_TIMER_L_TTR_T 12L
#undef com_nokia_comm_wap_wps_Bearer_WDP_D_TIMER_GTR_T
#define com_nokia_comm_wap_wps_Bearer_WDP_D_TIMER_GTR_T 13L
#undef com_nokia_comm_wap_wps_Bearer_WDP_D_TIMER_WAIT_T
#define com_nokia_comm_wap_wps_Bearer_WDP_D_TIMER_WAIT_T 14L
#undef com_nokia_comm_wap_wps_Bearer_WDP_D_BEARER_TYPE
#define com_nokia_comm_wap_wps_Bearer_WDP_D_BEARER_TYPE 15L
#undef com_nokia_comm_wap_wps_Bearer_WDP_D_CAS_CACHE_USE
#define com_nokia_comm_wap_wps_Bearer_WDP_D_CAS_CACHE_USE 16L
#undef com_nokia_comm_wap_wps_Bearer_WDP_D_CAS_CACHE_T
#define com_nokia_comm_wap_wps_Bearer_WDP_D_CAS_CACHE_T 17L
#undef com_nokia_comm_wap_wps_Bearer_WDP_D_CAS_FLUSH_LIMIT
#define com_nokia_comm_wap_wps_Bearer_WDP_D_CAS_FLUSH_LIMIT 18L
#undef com_nokia_comm_wap_wps_Bearer_WDP_D_CAS_BAG_ELEM_LIMIT
#define com_nokia_comm_wap_wps_Bearer_WDP_D_CAS_BAG_ELEM_LIMIT 19L
#undef com_nokia_comm_wap_wps_Bearer_WDP_D_CAS_CACHE_EXPIRATION_LIMIT
#define com_nokia_comm_wap_wps_Bearer_WDP_D_CAS_CACHE_EXPIRATION_LIMIT 20L
#undef com_nokia_comm_wap_wps_Bearer_WDP_D_SAR_MEDIAN_ROUND_TRIP_TIME
#define com_nokia_comm_wap_wps_Bearer_WDP_D_SAR_MEDIAN_ROUND_TRIP_TIME 21L
#undef com_nokia_comm_wap_wps_Bearer_WDP_D_SAR_PACKET_DELAY_TIME
#define com_nokia_comm_wap_wps_Bearer_WDP_D_SAR_PACKET_DELAY_TIME 22L
#undef com_nokia_comm_wap_wps_Bearer_WDP_D_SAR_GROUP_DELAY_TIME
#define com_nokia_comm_wap_wps_Bearer_WDP_D_SAR_GROUP_DELAY_TIME 23L
#undef com_nokia_comm_wap_wps_Bearer_WDP_D_SAR_MAX_GROUP_SIZE
#define com_nokia_comm_wap_wps_Bearer_WDP_D_SAR_MAX_GROUP_SIZE 24L
#undef com_nokia_comm_wap_wps_Bearer_WDP_SUCCESS
#define com_nokia_comm_wap_wps_Bearer_WDP_SUCCESS 0L
#undef com_nokia_comm_wap_wps_Bearer_WDP_ERROR
#define com_nokia_comm_wap_wps_Bearer_WDP_ERROR 1L
/*
 * Class:     com_nokia_comm_wap_wps_Bearer
 * Method:    install
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_nokia_comm_wap_wps_Bearer_install
  (JNIEnv *, jobject);

/*
 * Class:     com_nokia_comm_wap_wps_Bearer
 * Method:    uninstall
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_nokia_comm_wap_wps_Bearer_uninstall
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
