/*
* Copyright (c) 2000 - 2005 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:  
 *
*/


/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nokia_comm_wap_wps_HeaderCodec */

#ifndef _Included_com_nokia_comm_wap_wps_HeaderCodec
#define _Included_com_nokia_comm_wap_wps_HeaderCodec
#ifdef __cplusplus
extern "C" {
#endif
#undef com_nokia_comm_wap_wps_HeaderCodec_DEFAULT_ENCODE_BUF_LEN
#define com_nokia_comm_wap_wps_HeaderCodec_DEFAULT_ENCODE_BUF_LEN 1024L
#undef com_nokia_comm_wap_wps_HeaderCodec_DEFAULT_DECODE_BUF_LEN
#define com_nokia_comm_wap_wps_HeaderCodec_DEFAULT_DECODE_BUF_LEN 2048L
/* Inaccessible static: enc_buf_len */
/* Inaccessible static: dec_buf_len */
/* Inaccessible static: OPT_NONE */
/* Inaccessible static: OPT_CONTENT_TYPE_FIRST */
/* Inaccessible static: cEncErrorMessages */
/* Inaccessible static: cDecErrorMessages */
/*
 * Class:     com_nokia_comm_wap_wps_HeaderCodec
 * Method:    cDecode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_nokia_comm_wap_wps_HeaderCodec_cDecode
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_nokia_comm_wap_wps_HeaderCodec
 * Method:    cEncode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_nokia_comm_wap_wps_HeaderCodec_cEncode
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
