/*
* Copyright (c) 2000 - 2005 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:  
 *
*/


/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nokia_comm_wap_wps_Stack */

#ifndef _Included_com_nokia_comm_wap_wps_Stack
#define _Included_com_nokia_comm_wap_wps_Stack
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nokia_comm_wap_wps_Stack
 * Method:    cFinish
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_nokia_comm_wap_wps_Stack_cFinish
  (JNIEnv *, jobject);

/*
 * Class:     com_nokia_comm_wap_wps_Stack
 * Method:    cInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_nokia_comm_wap_wps_Stack_cInit
  (JNIEnv *, jobject);

/*
 * Class:     com_nokia_comm_wap_wps_Stack
 * Method:    cSetDebugLog
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_nokia_comm_wap_wps_Stack_cSetDebugLog
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_nokia_comm_wap_wps_Stack
 * Method:    cSetLog
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_nokia_comm_wap_wps_Stack_cSetLog
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_nokia_comm_wap_wps_Stack
 * Method:    cSetUseCodec
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_nokia_comm_wap_wps_Stack_cSetUseCodec
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
