/*
* Copyright (c) 2000 - 2005 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:  
 *
*/


/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nokia_wap_sdk_http_GatewayLoader */

#ifndef _Included_com_nokia_wap_sdk_http_GatewayLoader
#define _Included_com_nokia_wap_sdk_http_GatewayLoader
#ifdef __cplusplus
extern "C" {
#endif
#undef com_nokia_wap_sdk_http_GatewayLoader_DEFAULT_CLESS_PORT
#define com_nokia_wap_sdk_http_GatewayLoader_DEFAULT_CLESS_PORT 9200L
#undef com_nokia_wap_sdk_http_GatewayLoader_DEFAULT_CMODE_PORT
#define com_nokia_wap_sdk_http_GatewayLoader_DEFAULT_CMODE_PORT 9201L
#undef com_nokia_wap_sdk_http_GatewayLoader_DEFAULT_SEC_CLESS_PORT
#define com_nokia_wap_sdk_http_GatewayLoader_DEFAULT_SEC_CLESS_PORT 9202L
#undef com_nokia_wap_sdk_http_GatewayLoader_DEFAULT_SEC_CMODE_PORT
#define com_nokia_wap_sdk_http_GatewayLoader_DEFAULT_SEC_CMODE_PORT 9203L
#undef com_nokia_wap_sdk_http_GatewayLoader_DEFAULT_CL_LOCAL_PORT
#define com_nokia_wap_sdk_http_GatewayLoader_DEFAULT_CL_LOCAL_PORT 0L
#undef com_nokia_wap_sdk_http_GatewayLoader_DEFAULT_CO_LOCAL_PORT
#define com_nokia_wap_sdk_http_GatewayLoader_DEFAULT_CO_LOCAL_PORT 0L
#undef com_nokia_wap_sdk_http_GatewayLoader_DEFAULT_SEC_CL_LOCAL_PORT
#define com_nokia_wap_sdk_http_GatewayLoader_DEFAULT_SEC_CL_LOCAL_PORT 0L
#undef com_nokia_wap_sdk_http_GatewayLoader_DEFAULT_SEC_CO_LOCAL_PORT
#define com_nokia_wap_sdk_http_GatewayLoader_DEFAULT_SEC_CO_LOCAL_PORT 0L
#undef com_nokia_wap_sdk_http_GatewayLoader_DEFAULT_CLESS_PUSH_PORT
#define com_nokia_wap_sdk_http_GatewayLoader_DEFAULT_CLESS_PUSH_PORT 2948L
#undef com_nokia_wap_sdk_http_GatewayLoader_DEFAULT_CLESS_SEC_PUSH_PORT
#define com_nokia_wap_sdk_http_GatewayLoader_DEFAULT_CLESS_SEC_PUSH_PORT 2949L
#undef com_nokia_wap_sdk_http_GatewayLoader_DEFAULT_CMODE_PUSH_PORT
#define com_nokia_wap_sdk_http_GatewayLoader_DEFAULT_CMODE_PUSH_PORT 9209L
#undef com_nokia_wap_sdk_http_GatewayLoader_DEFAULT_WSP_TIMEOUT
#define com_nokia_wap_sdk_http_GatewayLoader_DEFAULT_WSP_TIMEOUT 2000L
#undef com_nokia_wap_sdk_http_GatewayLoader_DEFAULT_POLLING_TIMEOUT
#define com_nokia_wap_sdk_http_GatewayLoader_DEFAULT_POLLING_TIMEOUT 1000L
#undef com_nokia_wap_sdk_http_GatewayLoader_DEFAULT_PUSH_TIMEOUT
#define com_nokia_wap_sdk_http_GatewayLoader_DEFAULT_PUSH_TIMEOUT 10000L
#undef com_nokia_wap_sdk_http_GatewayLoader_MAX_SESSION_REDIRECTS
#define com_nokia_wap_sdk_http_GatewayLoader_MAX_SESSION_REDIRECTS 7L
#undef com_nokia_wap_sdk_http_GatewayLoader_DEFAULT_KEYREFRESH_RATE
#define com_nokia_wap_sdk_http_GatewayLoader_DEFAULT_KEYREFRESH_RATE 4L
#undef com_nokia_wap_sdk_http_GatewayLoader_DEFAULT_SNM
#define com_nokia_wap_sdk_http_GatewayLoader_DEFAULT_SNM 2L
/* Inaccessible static: DEFAULT_CIPHER_SUITES */
/* Inaccessible static: g_wap_stack */
/* Inaccessible static: g_bearer */
/* Inaccessible static: g_useJavaCodec */
/* Inaccessible static: instance */
/* Inaccessible static: fatalErrorHandler */
/* Inaccessible static: preferences */
/* Inaccessible static: g_transaction_ctr */
/* Inaccessible static: g_timeout */
/* Inaccessible static: g_debug_on */
/* Inaccessible static: class_00024java_00024lang_00024Boolean */
/* Inaccessible static: class_00024com_00024nokia_00024wap_00024sdk_00024http_00024GatewayLoader */
/* Inaccessible static: class_00024java_00024lang_00024String */
/* Inaccessible static: class_00024java_00024lang_00024Integer */
/* Inaccessible static: class_00024java_00024util_00024Vector */
/* Inaccessible static: class_00024java_00024lang_00024Byte */
/* Inaccessible static: class_00024javax_00024swing_00024event_00024ChangeListener */
/*
 * Class:     com_nokia_wap_sdk_http_GatewayLoader
 * Method:    registerNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_nokia_wap_sdk_http_GatewayLoader_registerNativeObject
  (JNIEnv *, jobject);
/*
 * Class:     com_nokia_wap_sdk_http_GatewayLoader
 * Method:    installCBearer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_nokia_wap_sdk_http_GatewayLoader_installCBearer
  (JNIEnv *, jclass);



#ifdef __cplusplus
}
#endif
#endif
